backend:
  name: github
  branch: v2019 # Branch to update (optional; defaults to master)
media_folder: "static/uploads" # Media files will be stored in the repo under static/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads

slug:
  clean_accents: true

collections:
  - name: "menu" # Used in routes, e.g., /admin/collections/blog
    label: "Menu" # Used in the UI
    files:
      - file: "content/menu.json"
        label: "Menu"
        format: "json"
        name: "menu"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "menu" }
          - {
            label: "Menu Items",
            name: "menuItems",
            widget: "list",
            fields:
              [
              { label: "Title", name: "title", widget: "string"},
              { label: "Visible", name: "visible", widget: "boolean", default: true},
              { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external"], default: "internal" },
              { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." }
              ]
          }
