backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "assets/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "hero" # Used in routes, e.g., /admin/collections/blog
    label: "Hero" # Used in the UI
    folder: "_contents/hero" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
